require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "notificare-1.0.2.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Notificare SDK" \
		--summary="Rich and interactive push notifications for iOS, Android and Web. Enhance your apps with location based messages that really work." \
		--publisher="Notificare B.V." \
		--website="http://notifica.re" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/notificare_128x128.png" \
		--icon="icons/notificare_512x512.png" \
		--library="ios":"../Notificare.iOS/bin/Release/Notificare.iOS.dll" \
		--library="android":"../Notificare.Android/bin/Release/Notificare.Android.dll" \
		--sample="iOS Sample. Demonstrates Notificare on iOS.":"samples/Notificare.iOS.SampleApp/Notificare.iOS.SampleApp.sln"
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end

