#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Notificare.Sample.Android.Resource", IsApplication=true)]

namespace Notificare.Sample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_horizontal_margin = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int activity_vertical_margin = 2131296257;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_plusone_medium_off_client = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_plusone_small_off_client = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_standard_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_tall_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int hybrid = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int list = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int message = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int myButton = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int none = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int normal = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int notificare_callback_image = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int notificare_callback_message = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int notificare_send_button = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int notification_fragment = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int satellite = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int terrain = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notificare_alert_dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notificare_callback_camera = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notificare_callback_camera_keyboard = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notificare_callback_keyboard = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notificare_notification_container = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notificare_notification_fragment = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070030
			public const int app_name = 2131165232;
			
			// aapt resource value: 0x7f070015
			public const int auth_client_needs_enabling_title = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int auth_client_needs_installation_title = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int auth_client_needs_update_title = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int auth_client_play_services_err_notification_msg = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int auth_client_requested_by_msg = 2131165209;
			
			// aapt resource value: 0x7f070014
			public const int auth_client_using_bad_version_title = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_enable_button = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_enable_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_install_button = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_google_play_services_install_text_phone = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_install_text_tablet = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_install_title = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_invalid_account_title = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_network_error_text = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_network_error_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_unknown_issue = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_unsupported_date_text = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_unsupported_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_unsupported_title = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_update_button = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_update_text = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_update_title = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int common_signin_button_text = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int common_signin_button_text_long = 2131165203;
			
			// aapt resource value: 0x7f07002e
			public const int hello = 2131165230;
			
			// aapt resource value: 0x7f07001a
			public const int location_client_powered_by_google = 2131165210;
			
			// aapt resource value: 0x7f070023
			public const int notificare_action_error_no_dialer = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int notificare_action_error_no_email_clients = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int notificare_action_error_no_sms_clients = 2131165218;
			
			// aapt resource value: 0x7f070026
			public const int notificare_action_failed = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int notificare_action_progress = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int notificare_action_success = 2131165221;
			
			// aapt resource value: 0x7f07001d
			public const int notificare_action_title_intent_email = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int notificare_action_title_intent_passbook = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int notificare_action_title_intent_sms = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int notificare_action_title_intent_telephone = 2131165215;
			
			// aapt resource value: 0x7f07001c
			public const int notificare_notification_error_gms_connect = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int notificare_notification_has_action = 2131165211;
			
			// aapt resource value: 0x7f070029
			public const int notificare_text_back = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int notificare_text_cancel = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int notificare_text_message_hint = 2131165226;
			
			// aapt resource value: 0x7f070027
			public const int notificare_text_send = 2131165223;
			
			// aapt resource value: 0x7f07002f
			public const int open_user_preferences = 2131165231;
			
			// aapt resource value: 0x7f07002b
			public const int pref_location_services_title = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int pref_summary_location_updates = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int pref_title_location_updates = 2131165229;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppBaseTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int AppTheme = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int notificare_preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
